name: Tarot by HiC
favicon: null
layout_spectrum: 0.30324719846248627
typography_spectrum: 0.5869797284249216
title: Tarot by HiC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.24444231134839356
  lightness: 0.24417071416974068
  saturation: 0.19783763261511922
  rhythmicContrast: 0.9456911899615079
purpose: []
