typography_spectrum: 0.22397
color:
  brandColors:
    - '#9d85c3'
    - '#beafd6'
    - '#e2dbec'
    - '#010102'
    - '#5b4778'
  brandStrength: 0.24444231134839356
  lightness: 0.24417071416974068
  saturation: 0.19783763261511922
  rhythmicContrast: 0.9456911899615079
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75073
analytics:
  google: null
  facebook: null
  twitter: null
name: Tarot by HiC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 'http://www.tarotbyhic.net'
    url: 'http://www.tarotbyhic.net'
    name: Tarot by HiC
    type: external
  - id: 'http://www.tarotbyhic.net/cardoftheday.html'
    url: 'http://www.tarotbyhic.net/cardoftheday.html'
    name: Card of the Day
    type: external
favicon: null
title: Tarot by HiC
purpose: []
