layout_spectrum: 0.5406801356002688
typography_spectrum: 0.5756436821538955
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.8985927912872285
  lightness: 0.7376404898241162
  saturation: 0.9032760583795607
  rhythmicContrast: 0.24281469779089093
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/64699097-c3d6-4d03-a7df-4f24a7cf336d.png
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: HiC Luttmers
  email: hic@tarotbyhic.net
  url: 'http://www.tarotbyhic.net'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/85219b1e-4d99-4c81-85f6-1b94bd3f71d9.jpg
name: Tarot by HiC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Tarot by HiC
    url: 'http://www.tarotbyhic.net'
    type: external
  - name: Card of the Day
    url: 'http://www.tarotbyhic.net/cardoftheday.html'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e7fa0685-7ce6-4a66-b3e3-d12080408fe1.jpg
title: Tarot by HiC
description: "Insight •\_Information • Empowerment •\_Enlightenment"
purpose: []
