name: Tarot by HiC
favicon: null
layout_spectrum: 0.75073
typography_spectrum: 0.22397
title: Tarot by HiC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9d85c3'
    - '#beafd6'
    - '#e2dbec'
    - '#010102'
    - '#5b4778'
  brandStrength: 0.24444231134839356
  lightness: 0.24417071416974068
  saturation: 0.19783763261511922
  rhythmicContrast: 0.9456911899615079
purpose: []
